### PR TITLE
Update README.md with spelling corrections

### PR DESCRIPTION
**Pull request by Br3W7h1S**
Spelling corrections made to README.md, as per document instructions.

### CODE REVIEW

**Review by AndrewRathbun — APPROVED** [review]

**Comment by AndrewRathbun** [comment]
Nice work!

**Comment by AndrewRathbun** [comment]
@Br3W7h1S feel free to add some new spelling errors for the next person 👍

**Comment by AndrewRathbun** [comment]
In a new PR, of course. Now that this one is merged you'd have to do a new one. So update your fork using fetch from upstream and then add whatever you want, if you so choose.

**Comment by Br3W7h1S** [comment]
> In a new PR, of course. Now that this one is merged you'd have to do a new one. So update your fork using fetch from upstream and then add whatever you want, if you so choose.

I will give this a try!  Thanks! :D

**Pull request merged**
